server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
#  config:
#    import: optional:file:.env[.properties]  # .env import
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shopdb?serverTimezone=Asia/Seoul
    username: smuser
    password: 111111
mybatis:
  type-aliases-package: edu.sm.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
app:
  key: ${mykey}
  url:
    server-url: https://210.119.34.77:8443
    chatbot: https://3vd0tljt1i.apigw.ntruss.com/custom/v1/16309/fc8085c312a614ef5f60fb796f3f9996ba5c6d29bb250a5437ba11bafc58f0bf
  dir:
    imgdir: file:///c:/springsm/imgs/
    uploadimgdir: c:/springsm/imgs/
    logdir: file:///c:/springsm/logs/
    readlogdir: c:/springsm/logs/